version: '3.8'

volumes:
  server-data: 
    driver: local

services:
  server:
    image: ghcr.io/bots-house/docker-telegram-bot-api:latest
    environment: 
      TELEGRAM_API_ID: ****************
      TELEGRAM_API_HASH: ******************************
    command: 
      - --dir=/var/lib/telegram-bot-api
      - --verbosity=2
    volumes: 
      - server-data:/var/lib/telegram-bot-api
    ports:
      - 8081:8081

  app: # New service
    image: telegram_bot:latest
    depends_on:
      - server
    environment:
      # If your application uses environment variables to know where to connect, set them here
      SERVER_URL: http://server:8081
    ports:
      - 8000:8000 # Assuming your app runs on port 8000, modify accordingly
