version: '3.8'

volumes:
  server-data:

services:
  app: # New service
    image: telegram_bot:latest
    environment:
      # If your application uses environment variables to know where to connect, set them here
#      SERVER_URL: http://server:8081
#      TELEGRAM_BASE_URL: http://server:8081/bot
#      TELEGRAM_BASE_FILE_URL: http://server:8081/file/bot
      TELEGRAM_ALLOWED_IDS: ${TELEGRAM_ALLOWED_IDS}
      OPENAI_API_KEY: ${TELEGRAM_OPENAI_API_KEY}
      TELEGRAM_API_TOKEN: ${TELEGRAM_API_TOKEN}
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
    volumes:
      - server-data:/mnt
    ports:
      - 8081:8081 # Assuming your app runs on port 8000, modify accordingly

